services:
  angular: 
    networks:
      - balance
    depends_on:
      - node
    build: 
      context: ./angular
      dockerfile: ./Dockerfile
    ports:
      - "4200:4200"
    env_file:
      - ./angular/.env
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./angular/src:/app/src
      - ./angular/angular.json:/app/angular.json
      - ./angular/tsconfig.json:/app/tsconfig.json
  node:
    networks:
      - balance
    build: 
      context: ./backend/node
      dockerfile: ./Dockerfile
    ports: 
      - "3000:3000"
    env_file: ./backend/node/.env
    
  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:



networks:
  balance:
    name: balance