services:
  angular: 
    networks:
      - balance
    depends_on:
      - node
    build: 
      context: ./angular
      dockerfile: ./Dockerfile
    ports:
      - "4200:4200"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - GATEWAY=${GATEWAY}
    volumes:
      - ./angular/src:/app/src
      - ./angular/angular.json:/app/angular.json
      - ./angular/tsconfig.json:/app/tsconfig.json
  node:
    networks:
      - balance
    build: 
      context: ./backend/node
      dockerfile: ./Dockerfile
    ports: 
      - "3000:3000"
    environment:
      - PLAID_CLIENT_ID=${PLAID_CLIENT_ID}
      - PLAID_SECRET=${PLAID_SECRET}
      - PLAID_PRODUCTS=${PLAID_PRODUCTS}
      - PLAID_HOST=${PLAID_HOST}
      - PLAID_COUNTRY_CODES=${PLAID_COUNTRY_CODES}
      - PLAID_ENV=${PLAID_ENV}
      - PLAID_CLIENT_NAME=${PLAID_CLIENT_NAME}
      - PLAID_REDIRECT_URI=${PLAID_REDIRECT_URI}
      - MONGO_URL=${MONGO_URL}
    
  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:



networks:
  balance:
    name: balance